### PR TITLE
shenme changes

### PR DESCRIPTION
**Pull request by bradington014**
heheheheh

### CODE REVIEW

**Comment by qupotter** [comment]
Bradley what is this I told you to make 5 new subsystems and a command to utilize the new PID loops with feedforward and closed loop control on the encoders.

**Comment by qupotter** [comment]
I'm cutting your pay in half. My senior developer doesn't need 300k to make breaking bad poetry

**Comment by qupotter** [comment]
@bradington014

**Comment by bradington014** [comment]
no i will be taking the money and the code with me you cant stop me

i will escape your grasp

**Comment by bradington014** [comment]
ratio

**Pull request merged**
